metadata:
  repo_dir: ${phantom-touch:}
  data_dir: /mnt/dataset_drive/ayad/phantom-touch
  model_dir: /mnt/dataset_drive/ayad/phantom-touch
  experiment_name: white_cloth_exp
  experiment_specifics: white_nonreflective_cloth_light_on_ambient_light
sam2sieve:
  images_path : ${metadata.data_dir}/data/recordings/${metadata.experiment_name}/${metadata.experiment_specifics}/png_output/color_sample
  text_prompt : hand
  output_dir : ${metadata.data_dir}/data/output/${metadata.experiment_name}/${metadata.experiment_specifics}/sam2-sieve_output
sam2videoPredictor:
  sam2_checkpoint : ${metadata.model_dir}/models/sam2/checkpoints/sam2.1_hiera_large.pt #TODO:: change to the correct path
  model_cfg : configs/sam2.1/sam2.1_hiera_l.yaml # relative to sam2
  video_frames_dir : ${metadata.data_dir}/data/recordings/${metadata.experiment_name}/${metadata.experiment_specifics}/jpg_frames
  output_dir : ${metadata.data_dir}/data/output/${metadata.experiment_name}/${metadata.experiment_specifics}/sam2-vid_output/output_wf2_mask_video_{now}.mp4"