load_ckpt: /mnt/dataset_drive/ayad/phantom-touch/models/diffusion/latest.pth

pred_horizon: 4
obs_horizon: 4
action_horizon: 1

resnet: 'resnet18'

vision_feature_dim: 512
lowdim_obs_dim: 14
action_dim: 7

batch_size: 16
eval_batch_size: 16

num_diffusion_iters: 100
gpu_ids: [0]

use_wandb: True
wandb_project_name: "handover_diffusion"
run_name: first_run

num_epochs: 1000
eval_freq: 5
lr: 1e-4
weight_decay: 1e-6

model_save_freq: 10

